name: vkquake
version: 1.31.3
grade: stable
base: core24
summary: A Quake 1 port using Vulkan.
description: |
  Note:
  This package only provides the engine, you need a valid copy of the (proprietary) game data to launch the game.
  
  vkQuake is a Quake 1 port using Vulkan instead of OpenGL for rendering. It is based on the popular QuakeSpasm port and runs all mods compatible with it like Arcane Dimensions or In The Shadows.
  
  Compared to QuakeSpasm vkQuake also features a software Quake like underwater effect, has better color precision, generates mipmap for water surfaces at runtime and has native support for anti-aliasing and AF.
  
  vkQuake also serves as a Vulkan demo application that shows basic usage of the API. For example it demonstrates render passes & sub passes, pipeline barriers & synchronization, compute shaders, push & specialization constants, CPU/GPU parallelism and memory pooling.
  
  - Note to snap packagers:
   Additionally, other snaps can consume its content via a content interface plug and use 'vkquake-launch' to start the engine. Consuming snaps could use following snapcraft.yaml snippet to add the interface.
   
  plugs:
    quake-engine:
      content: quake-engine
      interface: content
      target: $SNAP/quake-engine
      default-provider: vkquake:quake-engine
   
  Within the consuming snap the content would be exposed at "$SNAP/quake-engine", ie:
     /snap/the-consuming-snap/current/quake-engine
     /var/lib/snapd/snap/the-consuming-snap/current/quake-engine
   
  Under certain circumstances it could be necessary to manually connect the interface, ie:
     snap connect the-consuming-snap:quake-engine vkquake:quake-engine
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:
  armhf:

apps:
  vkquake:
    command-chain:
      - bin/gpu-2404-wrapper
    command: bin/vkquake
    plugs: [ wayland, x11, desktop, home, opengl, audio-playback, removable-media, network, joystick ]
  vkquake-launch:
    command-chain:
      - bin/gpu-2404-wrapper
    command: bin/vkquake-launch
    plugs: [ wayland, x11, desktop, home, opengl, audio-playback, removable-media, network, joystick ]

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

slots:
  quake-engine:
    content: quake-engine
    interface: content
    read:
      - $SNAP

parts:
  sdl2-with-vulkan:
    source: https://www.libsdl.org/release/SDL2-2.30.10.tar.gz
    source-type: tar
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - make
      - build-essential
      - libgl1-mesa-dev
      - libpulse-dev
      - libvulkan-dev
      - libwayland-dev
      - libx11-dev
      - libxi-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxcb-randr0-dev
      - x11proto-xinerama-dev
    prime:
      - usr/lib
  vkquake:
    source: https://github.com/Novum/vkQuake.git
    source-type: git
    source-tag: 1.31.3
    plugin: meson
    build-packages:
      - meson
      - ninja-build
      - build-essential
      - glslang-tools
      - spirv-tools
      - libgl1-mesa-dev
      - libpulse-dev
      - libvulkan-dev
      - libwayland-dev
      - libvorbis-dev
      - libmad0-dev
    stage-packages:
      - libpulse0
      - libvorbis0a
      - libvorbisfile3
      - libmad0
      - zenity
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -a $CRAFT_PART_BUILD/vkquake $CRAFT_PART_INSTALL/bin/
      chmod 755 $CRAFT_PART_INSTALL/bin/vkquake
    after: [ sdl2-with-vulkan ]
    prime:
      - bin/
      - usr/
  wrapper:
    source: .
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat $CRAFT_PART_SRC/vkquake-launch | sed "s/@@ARCH_TRIPLET@@/$CRAFT_ARCH_TRIPLET_BUILD_FOR/g" > $CRAFT_PART_INSTALL/bin/vkquake-launch
      chmod 755 $CRAFT_PART_INSTALL/bin/vkquake-launch
    after: [ vkquake ]
  gpu-snap:
    after:
      - sdl2-with-vulkan
      - vkquake
      - wrapper
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      rm -rf ${CRAFT_PRIME}/usr/share/{doc,man}
    prime:
      - bin/gpu-2404-wrapper
